name: Update AQI Data on GitHub Pages

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-aqi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: false  # Disable default credentials

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "github-actions[bot]"

      - name: Fetch AQI Data
        run: |
          chmod +x fetch_aqi.sh
          ./fetch_aqi.sh

      - name: Push Updates
        run: |
          git add aqi_data.json
          git commit -m "Updated AQI Data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/nagateja8561/weo.git gh-pages
