name: Update AQI Data on GitHub Pages

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Allows manual execution

jobs:
  update-aqi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.email "nagateja8561@gmail.com"
          git config --global user.name "nagateja8561"

      - name: Fetch AQI Data
        run: |
          chmod +x fetch_aqi.sh
          ./fetch_aqi.sh

      - name: Push Updates
        run: |
          git add aqi_data.json
          git commit -m "Updated AQI Data - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin gh-pages
